INSERT INTO `positions` (`ID`, `positiontype`, `positionname`) VALUES ('', '0', 'Battalion Executive Officer');
INSERT INTO `positions` (`ID`, `positiontype`, `positionname`) VALUES ('', '0', 'Battalion Commanding Officer');
INSERT INTO `positions` (`ID`, `positiontype`, `positionname`) VALUES ('', '0', 'Battalion Sergeant Major');
INSERT INTO `positions` (`ID`, `positiontype`, `positionname`) VALUES ('', '1', 'Battalion Manpower Officer');
INSERT INTO `positions` (`ID`, `positiontype`, `positionname`) VALUES ('', '1', 'Battalion Intel Officer');
INSERT INTO `positions` (`ID`, `positiontype`, `positionname`) VALUES ('', '1', 'Battalion Operations Chief');
INSERT INTO `positions` (`ID`, `positiontype`, `positionname`) VALUES ('', '1', 'Battalion Training Chief ');
INSERT INTO `positions` (`ID`, `positiontype`, `positionname`) VALUES ('', '0', 'Battalion Comms Chief');
INSERT INTO `positions` (`ID`, `positiontype`, `positionname`) VALUES ('', '0', 'Battalion Surgeon');
INSERT INTO `positions` (`ID`, `positiontype`, `positionname`) VALUES ('', '0', 'Company Commander');
INSERT INTO `positions` (`ID`, `positiontype`, `positionname`) VALUES ('', '0', 'Company Executive Officer');
INSERT INTO `positions` (`ID`, `positiontype`, `positionname`) VALUES ('', '0', 'Company First Sergeant');
INSERT INTO `positions` (`ID`, `positiontype`, `positionname`) VALUES ('', '0', 'Company Joint Terminal Attack Controller');
INSERT INTO `positions` (`ID`, `positiontype`, `positionname`) VALUES ('', '0', 'Company Forward Radio Operator');
INSERT INTO `positions` (`ID`, `positiontype`, `positionname`) VALUES ('', '0', 'Platoon Leader');
INSERT INTO `positions` (`ID`, `positiontype`, `positionname`) VALUES ('', '0', 'Platoon Sergeant');
INSERT INTO `positions` (`ID`, `positiontype`, `positionname`) VALUES ('', '0', 'Squad Leader');
INSERT INTO `positions` (`ID`, `positiontype`, `positionname`) VALUES ('', '0', 'Fireteam Leader');
INSERT INTO `positions` (`ID`, `positiontype`, `positionname`) VALUES ('', '0', 'Assistant Automatic Rifleman');
INSERT INTO `positions` (`ID`, `positiontype`, `positionname`) VALUES ('', '0', 'Rifleman');
INSERT INTO `positions` (`ID`, `positiontype`, `positionname`) VALUES ('', '0', 'Squad Leader');
INSERT INTO `positions` (`ID`, `positiontype`, `positionname`) VALUES ('', '0', 'Machine Gun Squad Leader');
INSERT INTO `positions` (`ID`, `positiontype`, `positionname`) VALUES ('', '0', 'Machine Gun Team Leader');
INSERT INTO `positions` (`ID`, `positiontype`, `positionname`) VALUES ('', '0', 'Gunner');
INSERT INTO `positions` (`ID`, `positiontype`, `positionname`) VALUES ('', '0', 'Ammunition Man');
INSERT INTO `positions` (`ID`, `positiontype`, `positionname`) VALUES ('', '0', 'Lead Chief Petty Officer');
INSERT INTO `positions` (`ID`, `positiontype`, `positionname`) VALUES ('', '0', 'Lead Petty Officer');
INSERT INTO `positions` (`ID`, `positiontype`, `positionname`) VALUES ('', '0', 'Corpsman');
INSERT INTO `positions` (`ID`, `positiontype`, `positionname`) VALUES ('', '0', 'Armor Commander');
INSERT INTO `positions` (`ID`, `positiontype`, `positionname`) VALUES ('', '0', 'Armor Executive Officer');
INSERT INTO `positions` (`ID`, `positiontype`, `positionname`) VALUES ('', '0', 'Platoon Leader');
INSERT INTO `positions` (`ID`, `positiontype`, `positionname`) VALUES ('', '0', 'Platoon Sergeant');
INSERT INTO `positions` (`ID`, `positiontype`, `positionname`) VALUES ('', '0', 'Vehicle Commander');
INSERT INTO `positions` (`ID`, `positiontype`, `positionname`) VALUES ('', '0', 'Wing Commander');
INSERT INTO `positions` (`ID`, `positiontype`, `positionname`) VALUES ('', '0', 'Wing Executive Officer');
INSERT INTO `positions` (`ID`, `positiontype`, `positionname`) VALUES ('', '0', 'F/A-18C/D/E/F Pilot');
INSERT INTO `positions` (`ID`, `positiontype`, `positionname`) VALUES ('', '0', 'F/A-18D/F Weapon Systems Officer');
INSERT INTO `positions` (`ID`, `positiontype`, `positionname`) VALUES ('', '0', 'E/A-18G Pilot');
INSERT INTO `positions` (`ID`, `positiontype`, `positionname`) VALUES ('', '0', 'E/A-18G Weapon Systems Officer');
INSERT INTO `positions` (`ID`, `positiontype`, `positionname`) VALUES ('', '0', 'CH-53E Pilot');
INSERT INTO `positions` (`ID`, `positiontype`, `positionname`) VALUES ('', '0', 'CH-53E Pilot');
INSERT INTO `positions` (`ID`, `positiontype`, `positionname`) VALUES ('', '0', 'MH-60R Pilot');
INSERT INTO `positions` (`ID`, `positiontype`, `positionname`) VALUES ('', '0', 'MV-22B Pilot');