INSERT INTO `courses` (`ID`, `coursename`) VALUES ('', 'Recruit Training Battalion');
INSERT INTO `courses` (`ID`, `coursename`) VALUES ('', 'School of Infanty');
INSERT INTO `courses` (`ID`, `coursename`) VALUES ('', 'Lance Corporals Seminar');
INSERT INTO `courses` (`ID`, `coursename`) VALUES ('', 'Corporals Course');
INSERT INTO `courses` (`ID`, `coursename`) VALUES ('', 'Infantry Small Unit Leaders Course');
INSERT INTO `courses` (`ID`, `coursename`) VALUES ('', 'Infantry Officers Course');
INSERT INTO `courses` (`ID`, `coursename`) VALUES ('', 'Combat Life Savers Course');
INSERT INTO `courses` (`ID`, `coursename`) VALUES ('', 'Marine Corps Communications-Electionics Course');
INSERT INTO `courses` (`ID`, `coursename`) VALUES ('', 'Recruit Training Command');
INSERT INTO `courses` (`ID`, `coursename`) VALUES ('', 'Fleet Medical Training Battalion');
INSERT INTO `courses` (`ID`, `coursename`) VALUES ('', 'Machine Gunners Course');
INSERT INTO `courses` (`ID`, `coursename`) VALUES ('', 'Designated Marksman Course');
INSERT INTO `courses` (`ID`, `coursename`) VALUES ('', 'Career Course');
INSERT INTO `courses` (`ID`, `coursename`) VALUES ('', 'Advanced Course');
INSERT INTO `courses` (`ID`, `coursename`) VALUES ('', 'Master Sergeant/First Sergeant Seminar');
INSERT INTO `courses` (`ID`, `coursename`) VALUES ('', 'Sergeant Major Course');
INSERT INTO `courses` (`ID`, `coursename`) VALUES ('', 'Introductory Flight Screening');
INSERT INTO `courses` (`ID`, `coursename`) VALUES ('', 'Aviation Preflight Indoctrination');
INSERT INTO `courses` (`ID`, `coursename`) VALUES ('', 'Primary 1');
INSERT INTO `courses` (`ID`, `coursename`) VALUES ('', 'Primary 2');
INSERT INTO `courses` (`ID`, `coursename`) VALUES ('', 'Intermediate');
INSERT INTO `courses` (`ID`, `coursename`) VALUES ('', 'Advanced Strike');
INSERT INTO `courses` (`ID`, `coursename`) VALUES ('', 'AO \"A\" School');