INSERT INTO `positions` (`ID`, `positiontype`, `positionname`) VALUES (NULL, '0', 'Zeus');
INSERT INTO `positions` (`ID`, `positiontype`, `positionname`) VALUES (NULL, '1', 'Personnel Clerk');
INSERT INTO `positions` (`ID`, `positiontype`, `positionname`) VALUES (NULL, '1', 'Recruiter');
INSERT INTO `positions` (`ID`, `positiontype`, `positionname`) VALUES (NULL, '1', 'Intel Clerk');
INSERT INTO `positions` (`ID`, `positiontype`, `positionname`) VALUES (NULL, '1', 'Campaign Development');
INSERT INTO `positions` (`ID`, `positiontype`, `positionname`) VALUES (NULL, '1', 'Mission Creator');
INSERT INTO `positions` (`ID`, `positiontype`, `positionname`) VALUES (NULL, '1', 'Drill Instructor');
INSERT INTO `positions` (`ID`, `positiontype`, `positionname`) VALUES (NULL, '1', 'Machine Gunners Course Instructor');
INSERT INTO `positions` (`ID`, `positiontype`, `positionname`) VALUES (NULL, '1', 'Infantry Officers Course Instructor');
INSERT INTO `positions` (`ID`, `positiontype`, `positionname`) VALUES (NULL, '1', 'Infantry Small Unit Leaders Course Instructor');
INSERT INTO `positions` (`ID`, `positiontype`, `positionname`) VALUES (NULL, '1', 'Joint Terminal Attack Controller Instructor');
INSERT INTO `positions` (`ID`, `positiontype`, `positionname`) VALUES (NULL, '1', 'Marine Corps Communication-Electonics Instructor');
INSERT INTO `positions` (`ID`, `positiontype`, `positionname`) VALUES (NULL, '1', 'Fleet Medical Training Instructor');
INSERT INTO `positions` (`ID`, `positiontype`, `positionname`) VALUES (NULL, '1', 'Naval Air Training Instructor');
INSERT INTO `positions` (`ID`, `positiontype`, `positionname`) VALUES (NULL, '1', 'Logistics Instructor');
INSERT INTO `positions` (`ID`, `positiontype`, `positionname`) VALUES (NULL, '1', 'Artillery Instructor');
INSERT INTO `positions` (`ID`, `positiontype`, `positionname`) VALUES (NULL, '1', 'Engineering Instructor');
INSERT INTO `positions` (`ID`, `positiontype`, `positionname`) VALUES (NULL, '1', 'Designated Marksman Instructor');
INSERT INTO `positions` (`ID`, `positiontype`, `positionname`) VALUES (NULL, '1', 'Technical Support Personnel');
INSERT INTO `positions` (`ID`, `positiontype`, `positionname`) VALUES (NULL, '1', 'Server Technician ');
INSERT INTO `positions` (`ID`, `positiontype`, `positionname`) VALUES (NULL, '1', 'Teamspeak Developer');
INSERT INTO `positions` (`ID`, `positiontype`, `positionname`) VALUES (NULL, '1', 'Website Administrator');
